#!/usr/bin/env node
/**
 * build.js — Converts realistic_button_templates.yaml into a self-registering
 * Lovelace JS resource for custom:button-card.
 *
 * Usage:  node build.js
 * Output: dist/realistic-button-card.js
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const SRC = path.join(__dirname, 'dist', 'realistic_button_templates.yaml');
const OUT = path.join(__dirname, 'dist', 'realistic-button-card.js');

// ---------- read & parse ----------
const raw = fs.readFileSync(SRC, 'utf8');
const doc = yaml.load(raw);
const templates = doc.button_card_templates;

if (!templates || typeof templates !== 'object') {
  console.error('ERROR: No button_card_templates key found in YAML.');
  process.exit(1);
}

// ---------- serialise to JS source ----------
// We need JSON-like output but with support for multi-line strings.
// JSON.stringify works, but we convert long strings to template literals
// for readability.  Backticks inside values are escaped.

function serialiseValue(val, indent) {
  const pad = '  '.repeat(indent);
  const pad1 = '  '.repeat(indent + 1);

  if (val === null || val === undefined) return 'null';
  if (typeof val === 'boolean') return String(val);
  if (typeof val === 'number') return String(val);

  if (typeof val === 'string') {
    // For short single-line strings, use JSON quoting
    if (!val.includes('\n') && val.length < 120) {
      return JSON.stringify(val);
    }
    // Multi-line → template literal (escape backticks and ${)
    const escaped = val
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$\{/g, '\\${');
    return '`' + escaped + '`';
  }

  if (Array.isArray(val)) {
    if (val.length === 0) return '[]';
    const items = val.map(v => pad1 + serialiseValue(v, indent + 1));
    return '[\n' + items.join(',\n') + '\n' + pad + ']';
  }

  if (typeof val === 'object') {
    const keys = Object.keys(val);
    if (keys.length === 0) return '{}';
    const entries = keys.map(k => {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      return pad1 + safeKey + ': ' + serialiseValue(val[k], indent + 1);
    });
    return '{\n' + entries.join(',\n') + '\n' + pad + '}';
  }

  return JSON.stringify(val);
}

const templatesSource = serialiseValue(templates, 1);

// ---------- wrap in loader ----------
const version = require('./package.json').version || '1.0.0';

const output = `/**
 * Realistic Button Card Templates v${version}
 * Auto-registers button_card_templates into custom:button-card.
 *
 * Generated by build.js — do not edit by hand.
 * Edit dist/realistic_button_templates.yaml and run: node build.js
 */

(function () {
  'use strict';

  const CARD_NAME = 'realistic-button-card';
  const CARD_DESCRIPTION = 'Neumorphic button card templates with dynamic glow effects';
  const CARD_VERSION = '${version}';

  /* ── template definitions ──────────────────────────────────────── */

  const TEMPLATES = ${templatesSource};

  /* ── registration logic ────────────────────────────────────────── */

  /**
   * Traverse the DOM shadow roots to reach the Lovelace object,
   * then merge our templates into button_card_templates.
   */
  function getLovelace() {
    // Modern HA (2024+) path
    let root = document.querySelector('home-assistant');
    if (!root || !root.shadowRoot) return null;

    root = root.shadowRoot.querySelector('home-assistant-main');
    if (!root || !root.shadowRoot) return null;

    root = root.shadowRoot.querySelector('ha-panel-lovelace');
    if (!root || !root.shadowRoot) return null;

    root = root.shadowRoot.querySelector('hui-root');
    if (!root) return null;

    return root.lovelace || null;
  }

  function injectTemplates() {
    const ll = getLovelace();
    if (!ll || !ll.config) return false;

    if (!ll.config.button_card_templates) {
      ll.config.button_card_templates = {};
    }

    let injected = 0;
    for (const [name, tpl] of Object.entries(TEMPLATES)) {
      if (!ll.config.button_card_templates[name]) {
        ll.config.button_card_templates[name] = tpl;
        injected++;
      }
    }

    if (injected > 0) {
      console.info(
        '%c ' + CARD_NAME + ' %c v' + CARD_VERSION + ' %c registered ' + injected + ' template(s) ',
        'background:#1e88e5;color:#fff;font-weight:bold;border-radius:3px 0 0 3px;padding:2px 4px',
        'background:#333;color:#fff;padding:2px 4px',
        'background:#43a047;color:#fff;font-weight:bold;border-radius:0 3px 3px 0;padding:2px 4px'
      );
    }
    return true;
  }

  // Retry until Lovelace is available (HA loads asynchronously)
  let attempts = 0;
  const MAX_ATTEMPTS = 50;    // ~10 seconds
  const RETRY_MS = 200;

  function tryInject() {
    if (injectTemplates()) return;
    attempts++;
    if (attempts < MAX_ATTEMPTS) {
      setTimeout(tryInject, RETRY_MS);
    } else {
      console.warn(
        CARD_NAME + ': could not find Lovelace config after ' + MAX_ATTEMPTS +
        ' attempts.  Make sure custom:button-card is installed.'
      );
    }
  }

  // Start injection when the window is ready
  if (document.readyState === 'complete') {
    tryInject();
  } else {
    window.addEventListener('load', tryInject);
  }

  // Also listen for Lovelace rebuilds (dashboard switches, YAML reloads)
  window.addEventListener('lovelace-updated', function () {
    attempts = 0;
    tryInject();
  });

  /* ── HACS / card-picker registration ───────────────────────────── */

  window.customCards = window.customCards || [];
  window.customCards.push({
    type: CARD_NAME,
    name: 'Realistic Button Card Templates',
    description: CARD_DESCRIPTION,
    preview: false,
  });

})();
`;

fs.writeFileSync(OUT, output, 'utf8');
const sizeKB = (Buffer.byteLength(output, 'utf8') / 1024).toFixed(1);
console.log('✓ Built ' + OUT + '  (' + sizeKB + ' KB)');
