#!/usr/bin/env node
/**
 * build.js — Converts realistic_button_templates.yaml into a self-registering
 * Lovelace JS resource for custom:button-card.
 *
 * Usage:  node build.js
 * Output: dist/realistic-button-card.js
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const SRC = path.join(__dirname, 'dist', 'realistic_button_templates.yaml');
const OUT = path.join(__dirname, 'dist', 'realistic-button-card.js');

// ---------- read & parse ----------
const raw = fs.readFileSync(SRC, 'utf8');
const doc = yaml.load(raw);

// Support both formats: with or without the button_card_templates wrapper
const templates = doc.button_card_templates || doc;

if (!templates || typeof templates !== 'object') {
  console.error('ERROR: Could not parse templates from YAML.');
  process.exit(1);
}

// ---------- serialise to JS source ----------
// We need JSON-like output but with support for multi-line strings.
// JSON.stringify works, but we convert long strings to template literals
// for readability.  Backticks inside values are escaped.

function serialiseValue(val, indent) {
  const pad = '  '.repeat(indent);
  const pad1 = '  '.repeat(indent + 1);

  if (val === null || val === undefined) return 'null';
  if (typeof val === 'boolean') return String(val);
  if (typeof val === 'number') return String(val);

  if (typeof val === 'string') {
    // For short single-line strings, use JSON quoting
    if (!val.includes('\n') && val.length < 120) {
      return JSON.stringify(val);
    }
    // Multi-line → template literal (escape backticks and ${)
    const escaped = val
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$\{/g, '\\${');
    return '`' + escaped + '`';
  }

  if (Array.isArray(val)) {
    if (val.length === 0) return '[]';
    const items = val.map(v => pad1 + serialiseValue(v, indent + 1));
    return '[\n' + items.join(',\n') + '\n' + pad + ']';
  }

  if (typeof val === 'object') {
    const keys = Object.keys(val);
    if (keys.length === 0) return '{}';
    const entries = keys.map(k => {
      const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      return pad1 + safeKey + ': ' + serialiseValue(val[k], indent + 1);
    });
    return '{\n' + entries.join(',\n') + '\n' + pad + '}';
  }

  return JSON.stringify(val);
}

const templatesSource = serialiseValue(templates, 1);

// ---------- wrap in loader ----------
const version = require('./package.json').version || '1.0.0';

const output = `/**
 * Realistic Button Card Templates v${version}
 * Auto-registers button_card_templates into custom:button-card.
 *
 * Generated by build.js — do not edit by hand.
 * Edit dist/realistic_button_templates.yaml and run: node build.js
 */

(function () {
  'use strict';

  const CARD_NAME = 'realistic-button-card';
  const CARD_DESCRIPTION = 'Neumorphic button card templates with dynamic glow effects';
  const CARD_VERSION = '${version}';

  /* ── template definitions ──────────────────────────────────────── */

  const TEMPLATES = ${templatesSource};

  /* ── registration logic ────────────────────────────────────────── */

  /**
   * Merge TEMPLATES into a config object (does not overwrite existing).
   * Returns the number of templates injected.
   */
  function mergeInto(config) {
    if (!config || typeof config !== 'object') return 0;
    if (!config.button_card_templates) config.button_card_templates = {};
    var injected = 0;
    for (var name in TEMPLATES) {
      if (!TEMPLATES.hasOwnProperty(name)) continue;
      if (!config.button_card_templates[name]) {
        config.button_card_templates[name] = TEMPLATES[name];
        injected++;
      }
    }
    return injected;
  }

  function logSuccess(count, strategy) {
    if (count > 0) {
      console.info(
        '%c ' + CARD_NAME + ' %c v' + CARD_VERSION + ' %c ' + count + ' template(s) registered via ' + strategy + ' ',
        'background:#1e88e5;color:#fff;font-weight:bold;border-radius:3px 0 0 3px;padding:2px 4px',
        'background:#333;color:#fff;padding:2px 4px',
        'background:#43a047;color:#fff;font-weight:bold;border-radius:0 3px 3px 0;padding:2px 4px'
      );
    }
  }

  /* ─── Strategy 1: Monkey-patch button-card ─────────────────────
   *  Intercepts every button-card instance's \`lovelace\` property
   *  setter.  When HA passes the lovelace config to the card, we
   *  merge our templates before the card renders.  This is the most
   *  reliable approach because it works regardless of HA version or
   *  shadow DOM structure.
   */
  var patchApplied = false;

  function patchButtonCard() {
    if (patchApplied) return;
    var BtnCard = customElements.get('button-card');
    if (!BtnCard) return;
    patchApplied = true;

    var proto = BtnCard.prototype;

    // Find the existing property descriptor (LitElement reactive property or plain)
    var desc = null;
    var p = proto;
    while (p && !desc) {
      desc = Object.getOwnPropertyDescriptor(p, 'lovelace');
      if (!desc) p = Object.getPrototypeOf(p);
    }

    var privateName = '_lovelace';

    Object.defineProperty(proto, 'lovelace', {
      configurable: true,
      enumerable: true,
      set: function (value) {
        // Inject templates into the config the card is about to use
        if (value && value.config) {
          var n = mergeInto(value.config);
          logSuccess(n, 'button-card patch');
        }
        // Call original setter or fall back to storing on a private field
        if (desc && desc.set) {
          desc.set.call(this, value);
        } else {
          this[privateName] = value;
        }
      },
      get: function () {
        if (desc && desc.get) return desc.get.call(this);
        return this[privateName];
      }
    });

    console.info(CARD_NAME + ': button-card patched — templates will auto-inject');
  }

  // Wait for button-card to register, then patch it
  customElements.whenDefined('button-card').then(patchButtonCard);

  /* ─── Strategy 2: DOM traversal fallback ───────────────────────
   *  In case the monkey-patch misses (e.g. cards already rendered
   *  before our script loaded), also try to inject into the
   *  lovelace config via the DOM.  Tries multiple shadow DOM paths
   *  for compatibility across HA versions.
   */
  function getLovelaceConfig() {
    try {
      var ha = document.querySelector('home-assistant');
      if (!ha || !ha.shadowRoot) return null;
      var main = ha.shadowRoot.querySelector('home-assistant-main');
      if (!main || !main.shadowRoot) return null;

      // Try multiple panel paths for HA version compat
      var selectors = [
        'ha-panel-lovelace',        // standard
        'partial-panel-resolver',   // older HA
      ];
      for (var i = 0; i < selectors.length; i++) {
        var panel = main.shadowRoot.querySelector(selectors[i]);
        if (!panel) continue;
        var root = panel.shadowRoot
          ? panel.shadowRoot.querySelector('hui-root')
          : null;
        if (root && root.lovelace && root.lovelace.config) {
          return root.lovelace.config;
        }
        // Also check for lovelace directly on the panel
        if (panel.lovelace && panel.lovelace.config) {
          return panel.lovelace.config;
        }
      }
    } catch (e) { /* swallow */ }
    return null;
  }

  var domAttempts = 0;
  function tryDomInject() {
    var config = getLovelaceConfig();
    if (config) {
      var n = mergeInto(config);
      logSuccess(n, 'DOM injection');
      return;
    }
    domAttempts++;
    if (domAttempts < 60) setTimeout(tryDomInject, 250);
  }

  if (document.readyState === 'complete') {
    setTimeout(tryDomInject, 100);
  } else {
    window.addEventListener('load', function () { setTimeout(tryDomInject, 100); });
  }

  /* ─── Strategy 3: Re-inject on dashboard navigation ────────── */
  window.addEventListener('location-changed', function () {
    domAttempts = 0;
    setTimeout(tryDomInject, 300);
  });

  /* ── HACS / card-picker registration ───────────────────────────── */

  window.customCards = window.customCards || [];
  window.customCards.push({
    type: CARD_NAME,
    name: 'Realistic Button Card Templates',
    description: CARD_DESCRIPTION,
    preview: false,
  });

})();
`;

fs.writeFileSync(OUT, output, 'utf8');
const sizeKB = (Buffer.byteLength(output, 'utf8') / 1024).toFixed(1);
console.log('✓ Built ' + OUT + '  (' + sizeKB + ' KB)');
